title: A. Panizo
description: Senior Product Engineer and Product Manager
baseurl: "/portfolio"
url: "https://alvaropanizo.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Asset settings
sass:
  sass_dir: _sass
  style: compressed

# Include settings
include:
  - assets
  - .nojekyll
  - _sass

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Collections
collections:
  experience:
    output: true
  education:
    output: true
  projects:
    output: true

# Asset paths
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/css"
    values:
      css: true
  - scope:
      path: "assets/js"
    values:
      js: true

# Theme specific settings
logo: "/assets/img/logo.png"
show_downloads: false 