title: A. Panizo
description: Senior Product Engineer and Product Manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alvaropanizo.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 