title: A. Panizo
description: Senior Product Engineer and Product Manager
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://alvaropanizo.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Asset settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/css"
    values:
      css: true
  - scope:
      path: "assets/js"
    values:
      js: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/fonts"
    values:
      font: true

# Include settings
include:
  - "assets"
  - "assets/css"
  - "assets/js"
  - "assets/images"
  - "assets/fonts"
  - ".nojekyll"

# Keep files
keep_files:
  - "assets"
  - ".nojekyll"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 