name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --baseurl "/portfolio" --trace --verbose
          
      - name: Run Build Script
        run: |
          mkdir -p scripts
          node scripts/build.js
          
      - name: Verify built assets
        run: |
          echo "Verifying built assets..."
          required_files=(
            "_site/assets/css/basecamp.css"
            "_site/assets/css/theme.css"
            "_site/assets/js/navigation.js"
            "_site/assets/js/scrolltext.js"
            "_site/assets/images/headshot.png"
            "_site/assets/fonts/Humane-Light.woff2"
            "_site/assets/fonts/Humane-Light.woff"
            "_site/assets/fonts/Humane-Light.ttf"
            "_site/assets/fonts/Humane-Light.eot"
            "_site/assets/fonts/Humane-Light.svg"
          )
          
          # Check each required file
          missing_files=()
          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "✓ Found built file: $file"
            else
              echo "✗ Missing built file: $file"
              missing_files+=("$file")
            fi
          done
          
          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "Error: Missing required built files:"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 